/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ContentTypeSlugImport } from './routes/$contentType.$slug'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContentTypeSlugRoute = ContentTypeSlugImport.update({
  id: '/$contentType/$slug',
  path: '/$contentType/$slug',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$contentType/$slug': {
      id: '/$contentType/$slug'
      path: '/$contentType/$slug'
      fullPath: '/$contentType/$slug'
      preLoaderRoute: typeof ContentTypeSlugImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$contentType/$slug': typeof ContentTypeSlugRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$contentType/$slug': typeof ContentTypeSlugRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$contentType/$slug': typeof ContentTypeSlugRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$contentType/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$contentType/$slug'
  id: '__root__' | '/' | '/$contentType/$slug'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentTypeSlugRoute: typeof ContentTypeSlugRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentTypeSlugRoute: ContentTypeSlugRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$contentType/$slug"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$contentType/$slug": {
      "filePath": "$contentType.$slug.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
