/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentTypeSlugRouteImport } from './routes/$contentType.$slug'
import { Route as OpengraphChar123ContentTypeChar125Char123SlugChar125RouteImport } from './routes/opengraph.{-$contentType}.{-$slug}'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTypeSlugRoute = ContentTypeSlugRouteImport.update({
  id: '/$contentType/$slug',
  path: '/$contentType/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OpengraphChar123ContentTypeChar125Char123SlugChar125Route =
  OpengraphChar123ContentTypeChar125Char123SlugChar125RouteImport.update({
    id: '/opengraph/{-$contentType}/{-$slug}',
    path: '/opengraph/{-$contentType}/{-$slug}',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$contentType/$slug': typeof ContentTypeSlugRoute
  '/opengraph/{-$contentType}/{-$slug}': typeof OpengraphChar123ContentTypeChar125Char123SlugChar125Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$contentType/$slug': typeof ContentTypeSlugRoute
  '/opengraph/{-$contentType}/{-$slug}': typeof OpengraphChar123ContentTypeChar125Char123SlugChar125Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$contentType/$slug': typeof ContentTypeSlugRoute
  '/opengraph/{-$contentType}/{-$slug}': typeof OpengraphChar123ContentTypeChar125Char123SlugChar125Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/$contentType/$slug'
    | '/opengraph/{-$contentType}/{-$slug}'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$contentType/$slug'
    | '/opengraph/{-$contentType}/{-$slug}'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/$contentType/$slug'
    | '/opengraph/{-$contentType}/{-$slug}'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ContentTypeSlugRoute: typeof ContentTypeSlugRoute
  OpengraphChar123ContentTypeChar125Char123SlugChar125Route: typeof OpengraphChar123ContentTypeChar125Char123SlugChar125Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$contentType/$slug': {
      id: '/$contentType/$slug'
      path: '/$contentType/$slug'
      fullPath: '/$contentType/$slug'
      preLoaderRoute: typeof ContentTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opengraph/{-$contentType}/{-$slug}': {
      id: '/opengraph/{-$contentType}/{-$slug}'
      path: '/opengraph/{-$contentType}/{-$slug}'
      fullPath: '/opengraph/{-$contentType}/{-$slug}'
      preLoaderRoute: typeof OpengraphChar123ContentTypeChar125Char123SlugChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ContentTypeSlugRoute: ContentTypeSlugRoute,
  OpengraphChar123ContentTypeChar125Char123SlugChar125Route:
    OpengraphChar123ContentTypeChar125Char123SlugChar125Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
