/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContentTypeSlugRouteImport } from './routes/$contentType.$slug'
import { ServerRoute as SitemapDotxmlServerRouteImport } from './routes/sitemap[.]xml'
import { ServerRoute as OpengraphChar123ContentTypeChar125Char123SlugChar125ServerRouteImport } from './routes/opengraph.{-$contentType}.{-$slug}'

const rootServerRouteImport = createServerRootRoute()

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentTypeSlugRoute = ContentTypeSlugRouteImport.update({
  id: '/$contentType/$slug',
  path: '/$contentType/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlServerRoute = SitemapDotxmlServerRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootServerRouteImport,
} as any)
const OpengraphChar123ContentTypeChar125Char123SlugChar125ServerRoute =
  OpengraphChar123ContentTypeChar125Char123SlugChar125ServerRouteImport.update({
    id: '/opengraph/{-$contentType}/{-$slug}',
    path: '/opengraph/{-$contentType}/{-$slug}',
    getParentRoute: () => rootServerRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$contentType/$slug': typeof ContentTypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$contentType/$slug': typeof ContentTypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$contentType/$slug': typeof ContentTypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$contentType/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$contentType/$slug'
  id: '__root__' | '/' | '/$contentType/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentTypeSlugRoute: typeof ContentTypeSlugRoute
}
export interface FileServerRoutesByFullPath {
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
  '/opengraph/{-$contentType}/{-$slug}': typeof OpengraphChar123ContentTypeChar125Char123SlugChar125ServerRoute
}
export interface FileServerRoutesByTo {
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
  '/opengraph/{-$contentType}/{-$slug}': typeof OpengraphChar123ContentTypeChar125Char123SlugChar125ServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/sitemap.xml': typeof SitemapDotxmlServerRoute
  '/opengraph/{-$contentType}/{-$slug}': typeof OpengraphChar123ContentTypeChar125Char123SlugChar125ServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths: '/sitemap.xml' | '/opengraph/{-$contentType}/{-$slug}'
  fileServerRoutesByTo: FileServerRoutesByTo
  to: '/sitemap.xml' | '/opengraph/{-$contentType}/{-$slug}'
  id: '__root__' | '/sitemap.xml' | '/opengraph/{-$contentType}/{-$slug}'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  SitemapDotxmlServerRoute: typeof SitemapDotxmlServerRoute
  OpengraphChar123ContentTypeChar125Char123SlugChar125ServerRoute: typeof OpengraphChar123ContentTypeChar125Char123SlugChar125ServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$contentType/$slug': {
      id: '/$contentType/$slug'
      path: '/$contentType/$slug'
      fullPath: '/$contentType/$slug'
      preLoaderRoute: typeof ContentTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/opengraph/{-$contentType}/{-$slug}': {
      id: '/opengraph/{-$contentType}/{-$slug}'
      path: '/opengraph/{-$contentType}/{-$slug}'
      fullPath: '/opengraph/{-$contentType}/{-$slug}'
      preLoaderRoute: typeof OpengraphChar123ContentTypeChar125Char123SlugChar125ServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentTypeSlugRoute: ContentTypeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  SitemapDotxmlServerRoute: SitemapDotxmlServerRoute,
  OpengraphChar123ContentTypeChar125Char123SlugChar125ServerRoute:
    OpengraphChar123ContentTypeChar125Char123SlugChar125ServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
